### PR TITLE
Improved the CI Workflow

### LINKED ISSUE #13: Improve CI
## User story - cache npm install artifacts

as a developer on this project,
I want fast and reliable builds,
so that I can deliver better software faster.

## User story - Improve CI failure reporting

As a developer on this project,
I want clear and specific error messages on CI failures,
so that I can deliver better software faster.

## Tasks

- [x] Cache npm install artifacts
- [x] Make error reporting from the `prettier` and `eslint` commands more verbose. right now, they just essentially say 'there's a problem,' which isn't very helpful.

## Expected outcome

All modifications should be contained within the `.github/workflows/lint.yml` file

### PR DESCRIPTION
**Pull request by tarunsinghofficial**
Fixes #13 

**Tasks Done**
- Cache npm install artifacts
- More verbose error reporting from the prettier and eslint commands.

**Files Changed:**
All modifications done within the `.github/workflows/lint.yml` file

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
Looks like you have a CI failure with prettier:

image

**Comment by tarunsinghofficial** [comment]
> Looks like you have a CI failure with prettier:
> 
> image



> Looks like you have a CI failure with prettier:
> 
> image



> Looks like you have a CI failure with prettier:
> 
> image

Yes, I'm still testing this. I'm new to CI/CD therefore, it is taking some time to me to learn.

**Comment by tarunsinghofficial** [comment]
Hi @aaronbrethorst,

The PR is now working correctly. Here is the ss of the logs:
image


Let me know if this is correct. 
Thanks

**Review by aaronbrethorst — APPROVED** [review]
great work!

**Pull request merged**
